import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import styles from '../styles/Home.module.css'
import About from '../components/About'

export default function Home() {
  return (
    <div className='bg-gray-800 text-white h-screen snap-y snap-mandatory overflow-scroll z-0'>
      <Head>
        <title>Vidit's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      {/* Hero */}
      <section id="hero" className='snap-start'>
        <Hero/>
      </section>
      {/* About */}
      <section id="" className='snap-center'>
        <About/>
      </section>
      {/* Experience */}

      {/* Skills */}

      {/* Projects */}

      {/* Contact Me */}


    </div>
  )
}
 